// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnh77O4f_iUWiUTd7Ww1_h0oanjhPHkrw',
    appId: '1:54790956783:web:705b061514b2aa5167dd1a',
    messagingSenderId: '54790956783',
    projectId: 'dermai-cdb0b',
    authDomain: 'dermai-cdb0b.firebaseapp.com',
    storageBucket: 'dermai-cdb0b.firebasestorage.app',
    measurementId: 'G-GD1V0QPFE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqjjPpktXQ3t0w13XxNxArQJbghi3YUe0',
    appId: '1:54790956783:android:95b4d23092d7ff6d67dd1a',
    messagingSenderId: '54790956783',
    projectId: 'dermai-cdb0b',
    storageBucket: 'dermai-cdb0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR-f1nKNqt1FTfUKpyW8qG-7M8lTxR7j0',
    appId: '1:54790956783:ios:06461de34d2bec5267dd1a',
    messagingSenderId: '54790956783',
    projectId: 'dermai-cdb0b',
    storageBucket: 'dermai-cdb0b.firebasestorage.app',
    iosBundleId: 'com.dermai.dermai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR-f1nKNqt1FTfUKpyW8qG-7M8lTxR7j0',
    appId: '1:54790956783:ios:06461de34d2bec5267dd1a',
    messagingSenderId: '54790956783',
    projectId: 'dermai-cdb0b',
    storageBucket: 'dermai-cdb0b.firebasestorage.app',
    iosBundleId: 'com.dermai.dermai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnh77O4f_iUWiUTd7Ww1_h0oanjhPHkrw',
    appId: '1:54790956783:web:286898a836d367f367dd1a',
    messagingSenderId: '54790956783',
    projectId: 'dermai-cdb0b',
    authDomain: 'dermai-cdb0b.firebaseapp.com',
    storageBucket: 'dermai-cdb0b.firebasestorage.app',
    measurementId: 'G-TE8VY3196B',
  );

}