import 'package:flutter/material.dart';
import '../widgets/custom_app_bar.dart';
import '../utils/app_colors.dart';
import '../utils/text_utils.dart';

class TermsOfUseScreen extends StatelessWidget {
  const TermsOfUseScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    return Scaffold(
      appBar: const CustomAppBar(
        showBackButton: true,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            Text(
              'Terms of Use',
              style: theme.textTheme.headlineMedium
                  ?.copyWith(fontWeight: FontWeight.bold),
            ),
            const SizedBox(height: 24),
            Container(
              margin: const EdgeInsets.symmetric(horizontal: 4),
              padding:
                  const EdgeInsets.symmetric(horizontal: 16.0, vertical: 8.0),
              decoration: BoxDecoration(
                color: AppColors.cherryBlossom,
                borderRadius: BorderRadius.circular(20),
              ),
              child: RichText(
                text: buildRichText(
                  '''
Welcome to DermAI! These **Terms of Use** (“Terms”) govern your access to and use of the DermAI mobile application (“App”) and related services. By downloading, installing, or using DermAI, you agree to these Terms. If you do not agree, please do not use the App.

1. Purpose of the App
DermAI is designed to assist users in understanding and managing their skin health by using AI technology to analyze skin images and provide informational insights. DermAI does *not* replace professional medical advice, diagnosis, or treatment.

2. Eligibility
You must be at least **18 years old**, or have the consent of a parent/guardian, to use DermAI.

3. User Responsibilities
You agree to provide accurate and clear images for analysis.
You will *not* upload harmful, obscene, or unlawful content.
You will *not* misuse the App for fraudulent or deceptive purposes.

4. AI Analysis Disclaimer
The results provided by DermAI are generated by artificial intelligence and are for *informational purposes only*. Always consult a licensed dermatologist for any medical concerns.

5. Intellectual Property
All content, design, and technology in DermAI are the property of DermAI and may *not* be copied, modified, or distributed without permission.

6. Limitation of Liability
DermAI and its developers are *not* liable for any direct or indirect damages arising from your use of the App, including reliance on AI-generated results.

7. Modifications to the Service
We may update or discontinue the App at any time without prior notice.

8. Governing Law
These terms and conditions are governed by the laws of the Republic of the Philippines.
                  ''',
                  baseStyle: theme.textTheme.bodySmall,
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
